dbt_script_runner_test:
  outputs:
    dev:
      dataset: DBT_DATASET_NAME
      method: oauth
      project: dev-demsstaff
      dataset: sbx_washingtona
      threads: 4
      type: bigquery
  target: dev

my-bigquery-db:
  outputs:
    dev:
      dataset: DBT_DATASET_NAME
      method: oauth
      project: dev-demsstaff
      dataset: sbx_washingtona
      threads: 4
      type: bigquery
  target: dev
